// <auto-generated />
using System;
using Innorik.Attendance.System.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Innorik.Attendance.System.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Innorik.Attendance.System.Application.Dtos.CommandDto+CreateCheckInDto", b =>
                {
                    b.Property<bool>("AtsActive")
                        .HasColumnType("bit");

                    b.Property<string>("AtsCheckInPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtsCheckInPictureHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtsFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtsLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CreateCheckInDtos");
                });

            modelBuilder.Entity("Innorik.Attendance.System.Application.Dtos.CommandDto+CreateCheckoutDto", b =>
                {
                    b.Property<byte[]>("AtsCheckOutPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("AtsCheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AtsFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtsLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CreateCheckoutDto");
                });

            modelBuilder.Entity("Innorik.Attendance.System.Application.Dtos.QueryDto+GetAllCheckInDto", b =>
                {
                    b.Property<bool>("AtsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("AtsCheckInPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("AtsCheckInPictureHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AtsCheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("AtsCheckOutPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("AtsCheckOutPictureHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AtsCheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AtsFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AtsIDpk")
                        .HasColumnType("int");

                    b.Property<string>("AtsLastName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("GetAllCheckInDtos");
                });

            modelBuilder.Entity("Innorik.Attendance.System.Domain.AttendanceSheet", b =>
                {
                    b.Property<int>("AtsIDpk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AtsIDpk"));

                    b.Property<bool>("AtsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("AtsCheckInPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("AtsCheckInPictureHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AtsCheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("AtsCheckOutPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("AtsCheckOutPictureHeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AtsCheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AtsFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtsLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AtsIDpk");

                    b.ToTable("AttendanceSheets");
                });
#pragma warning restore 612, 618
        }
    }
}
